# Generated by Django 5.2.3 on 2025-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_currentaffairpdf_delete_pdfupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaffairpdf',
            name='description',
        ),
        migrations.RemoveField(
            model_name='currentaffairpdf',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='currentaffairpdf',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
