# Generated by Django 5.2.3 on 2025-07-23 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_currentaffairpdf_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaffairpdf',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentaffairpdf',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 18, 18, 59, 577696, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
