# Generated by Django 5.2.3 on 2025-07-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dailyquiz_dailyquestion_dailyquizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquizsubmission',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyquizsubmission',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
