# Generated by Django 5.2.3 on 2025-07-31 10:10

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_dailyquizsubmission_skipped_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='dailyquestion',
            name='question_text_ml',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_a_ml',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_b_ml',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_c_ml',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_d_ml',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='question_text_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_a_en',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_b_en',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_c_en',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_d_en',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),

    ]
