# Generated by Django 5.2.3 on 2025-07-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20250731_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='question_text',
        ),
    ]
