# Generated by Django 5.2.3 on 2025-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_dailyquestion_option_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquestion',
            name='option_a_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='option_b_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='option_c_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='option_d_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='question_text_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
