# Generated by Django 5.2.3 on 2025-07-31 18:44

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_dailyquestion_option_a_en_and_more'),
    ]


operations = [
        migrations.CreateModel(
            name='PscPreviousYearQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('pdf_file', models.FileField(upload_to='pyqs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]


