# Generated by Django 5.2.3 on 2025-08-01 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_mocktestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PscMockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mocktestresult',
            old_name='submitted_at',
            new_name='taken_at',
        ),
        migrations.AlterUniqueTogether(
            name='mocktestresult',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PscMockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('psc_mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.pscmocktest')),
            ],
        ),
    ]
