# Generated by Django 5.2.3 on 2025-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrbpreviousyearquestion',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
