# Generated by Django 5.2.3 on 2025-08-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_rrbpreviousyearquestion_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mocktestresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mocktestresult',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
